default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: xpresschow_development
  username: postgres
  password: secret

test:
  <<: *default
  database: xpresschow_test
  username: postgres
  password: secret

production:
  <<: *default
  database: xpresschow_production
